# This compose file must be in the users working directory to map the development path

services:
    base:
        image: "inakivazquez/deustorl:base3"
        container_name: "rltrain"
        privileged: true
        tty: true
        stdin_open: true
        volumes:
            - .:/home/rl/my_scripts

    linux-cpu:
        extends:
            service: base
        network_mode: "host"
        privileged: true
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=$DISPLAY
            - SDL_VIDEODRIVER=x11

    linux-gpu:
        extends:
            service: linux-cpu
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          count: all

    windows-cpu:
        extends:
            service: base
        ports:
            - "6006:6006"
        privileged: true

    windows-gpu:
        extends:
            service: windows-cpu
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          count: all
