# This compose file must be in the users local directory, check this to avoid

services:
    rltrain-cpu:
        image: "inakivazquez/deustorl:base3"
        container_name: "rltrain"
        network_mode: "host"
        privileged: true
        tty: true
        stdin_open: true  
        volumes:
            - .:/home/rl/my_scripts
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=$DISPLAY
            - SDL_VIDEODRIVER=x11

    rltrain-gpu:
        extends:
            service: rltrain-cpu
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          count: all

    rltrain-windows-cpu:
        image: "inakivazquez/deustorl:base3"
        container_name: "rltrain"
        network_mode: "host"
        privileged: true
        tty: true
        stdin_open: true  
        volumes:
            - .:/home/rl/my_scripts

    rltrain-windows-gpu:
        extends:
            service: rltrain-windows-cpu
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          count: all
